### ISSUE TITLE
Cannot run msw-trpc with vitest

### ISSUE THREAD

**Issue by Q16solver** [maloguertin/msw-trpc#15]
**Describe the bug**
After upgrading msw-trpc from v1.2.1 -> v1.3.1, running vitest with my current setup is giving an ES module reference error, not quite sure what the issue could be.

![image](https://user-images.githubusercontent.com/50786287/235273593-cd5213ca-85ac-4a34-b3a8-65410b875d58.png)

**Expected behavior**
Vitest should run as normal before the upgrade.

**Versions**
typescript: v5.0.4
tRPC: v10.20.0
msw: v1.3.1

**Comment by Q16solver** [comment]
Update: I think it might just be a small issue with the package.json type, "type": "module" means that you declare it as ESM, please correct me if I'm wrong, so I believe we need to remove that

https://github.com/maloguertin/msw-trpc/commit/3293513c0a52abf416912a4e9e4a70c086eec45c

**Comment by maloguertin** [comment]
@Q16solver you're right, sorry about that I'll push a fix!

**Comment by maloguertin** [comment]
I'll close this as it should be solved by: https://github.com/maloguertin/msw-trpc/releases/tag/v1.3.2

**Comment by Q16solver** [comment]
@maloguertin Tested that it works now! closing this issue, thanks c:
