### ISSUE TITLE
trpc query firing before service worker is started

### ISSUE THREAD

**Issue by RL-adaptive** [maloguertin/msw-trpc#20]
**Describe the bug**
My app is using Nextjs although no SSR is being performed. Despite [deferring app bootstrapping](https://mswjs.io/docs/recipes/deferred-mounting)  as suggested [here](https://github.com/mswjs/msw/discussions/1049), trpc queries are fired before the MSW service worker initializes.
![trpc](https://github.com/maloguertin/msw-trpc/assets/106198976/8952207d-3782-4570-96a8-d96a5bb273f5)
I can confirm that subsequent queries are being intercepted by msw. Has anyone tried integrating msw-trpc with a Nextjs app before and encountered this issue? 

**To Reproduce**
1. Create a Nextjs app using msw-trpc for request mocking
2. Create a component that performs an immediate trpc query
3. Navigate to component with msw active
4. See query fired before service worker is loaded

**Expected behavior**
MSW service worker is finished loading before trpc queries are fired by react.

**Versions**
typescript: v4.7.4
tRPC: v10.9.0
msw: v1.2.2
next: v12.3.0

**Comment by maloguertin** [comment]
Hello! Have you tried with MSW standalone without msw-trpc? Trying to identify if this is related to this lib specifically.
