### ISSUE TITLE
Merged routes not working with latest trpc and msw-trpc

### ISSUE THREAD

**Issue by madi-tracksuit** [maloguertin/msw-trpc#29]
**Describe the bug**
When using msw-trpc with the latest version of trpc and merged / sub routers, every route exposes an (errornous) `mutation` method instead of the subrouter

**To Reproduce**
1. Create a trpc router with nested/merged routers
2. Setup msw-trpc
3. Try to access sub routers

**Comment by maloguertin** [comment]
I just created a branch to test it with the latest trpc: https://github.com/maloguertin/msw-trpc/tree/nested-merged-router
It seems to be working?

**Comment by madi-tracksuit** [comment]
Found it, I was on the `next` (v11) versions of trpc, downgrading back to v10 sorted it. Sorry for the false alarm!
