### ISSUE TITLE
Cannot trigger useQuery `error` or `isError` response in test

### ISSUE THREAD

**Issue by jchiversTRG** [maloguertin/msw-trpc#35]
`"msw-trpc": "^1.3.4",`

On my client I am making the call `const { data, isLoading, isError, error } = trpc.exampleFunction.useQuery()`.
If `isError` is true, I display the `error.message` in my screen.

This works fine when running my client app, however I cannot get the query to return the error in my unit tests (Jest / RN Testing Library). `error` remains undefined, and `isError` remains false.

Test setup:

Have tried:
```
const server = setupServer(
    trpcMsw.exampleFunction.query((req, res, ctx) => {
      throw new Error("test trpc error");
    }),
  );
```
  
  ```
const server = setupServer(
    trpcMsw.exampleFunction.query((req, res, ctx) => {
      throw new TRPCError({
        message: "test trpc error",
        code: 'NOT_FOUND',
      });
    }),
  );
```
  
  ```
const notFound = {
    error: {
      json: {
        message: 'NOT_FOUND',
        code: 404,
        data: {
          code: 'NOT_FOUND',
          httpStatus: 404,
          stack: '',
          path: '',
          zodError: null,
        },
      },
      meta: [],
    },
};

const server = setupServer(
    trpcMsw.exampleFunction.query((req, res, ctx) =>
      res(ctx.status(404), ctx.json(notFound)),
    ),
  );
```
  
The console output during the tests with the first two of the above shows a console warning with:
  `TRPCClientError: request to http://localhost:3000/trpc/exampleFunction?batch=1&input=%7B%220%22%3A%220%22%7D failed, reason: test trpc error`

And  the last shows a console warning with:
`TRPCClientError: Unable to transform response from server`

`error` and `isError` are undefined and false respectively, and never update.

Is it possible to get `isError` and the `error` object to be returned from this query in the test?

**Comment by danilofuchs** [comment]
My PR #34 addresses this issue

**Comment by klippx** [comment]
I am also trying to test error cases from the server (I am throwing TRPCError) but instead of a serialized response of `Failed to decompress` I am getting a plain `Failed to fetch` and no error handling is invoked in my component, which is using trpcs built in `useQuery` so it should work, its this mocking library that only works in happy path I guess?

```
  [cause]: TypeError: Failed to fetch
      at createNetworkError (file:///Users/MKLIPPIN/repos/graphql-federation-graphiql/node_modules/.pnpm/@mswjs+interceptors@0.25.15/node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:202:24)
      at globalThis.fetch (file:///Users/MKLIPPIN/repos/graphql-federation-graphiql/node_modules/.pnpm/@mswjs+interceptors@0.25.15/node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:113:31)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    cause: TRPCError: Failed to decompress
```
