### ISSUE TITLE
Serialization of request input with e.g., superjson

### ISSUE THREAD

**Issue by michealroberts** [maloguertin/msw-trpc#8]
First of all, this is an awesome piece of work for the tRPC community. Truly, awesome! However, I have noticed a bug when using with superjson serialisation on the input.

**Bug Description**

If we specify an input serialisation, such as superjson:

```ts
const msw = createTRPCMsw<AppRouter>({
  baseUrl: 'http://localhost:3000/trpc',
  transformer: {
    input: superjson,
    output: superjson
  }
})
```

I've found that `req.getInput()` gets incorrect types as:

<img width="398" alt="Screenshot 2023-02-21 at 12 12 39" src="https://user-images.githubusercontent.com/84131395/220341852-f0e7c233-911b-4719-9917-3302a9ec98dd.png">

A workaround would be to do some type madness (which, ideally, we would like to avoid):

```ts
const { json } = req.getInput() as unknown as {
    json: inferProcedureInput<AppRouter['observations']['all']>
}
```

**Replication Steps**

1. Create a router of your choice with some sample input. I've used skip and take from Prisma.io pagination terminology.
2. Create the mock service worker, as above, with your  `AppRouter` inferred type.
3. Check the type of `req.getInput()` and it will be missing the json key and the nested input types.

**Expected **

The expected behvaiour when we provide an input transform, that that transform is applied to the `req.getInput` return type.

**Versions**

typescript: v4.9.5
tRPC: v10.11.1
msw: v0.49.3
 msw-trpc: v1.2.0

**Comment by maloguertin** [comment]
Thanks for the issue I was planning on trying to handle transformer for input, I'll take a look.

**Comment by aulneau** [comment]
any updates on this? also running into this

**Comment by maloguertin** [comment]
Sorry I have been busy, this is still on my roadmap.

**Comment by maloguertin** [comment]
@aulneau  @michealroberts 

Could you guys take a look at https://github.com/maloguertin/msw-trpc/pull/10 

Basically I've made it so getInput correctly makes use of the transformer, so instead of receiving { json: {} } when calling getInput you will receive the input as your trpc handler would.

I also added getInput to mutation handlers.

**Comment by maloguertin** [comment]
Should be handled by https://github.com/maloguertin/msw-trpc/releases/tag/v1.3.0
