### ISSUE TITLE
Support for createTRPCReact (react query)

### ISSUE THREAD

**Issue by nterraza** [maloguertin/msw-trpc#9]
Is your feature request related to a problem? Please describe.
I have a standalone trpc server (with subscriptions) that I use with React, but msw-trpc doesn't support it yet or there are no examples of how to use it with react-query and createTRPCReact. It would be great to have some examples of how to use it with `useQuery`within a react component: https://trpc.io/docs/react

Describe the solution you'd like
I would like to have the ability to use msw-trpc with React and be able to mock subscriptions, mutations and queries.

Describe alternatives you've considered
Manually mocking the provider.

**Comment by maloguertin** [comment]
here's an example if you use [react-testing-library](https://testing-library.com/docs/react-testing-library/intro/).

```ts
// /tests/utils/trpc.ts

import { createTRPCMsw } from 'msw-trpc'

import type { AppRouter } from '../../server/router'

const trpc = createTRPCMsw<AppRouter>()

export default trpc
```

```ts
// /test/utils/renderer.tsx

import React from 'react'
import {render} from '@testing-library/react'

import { trpc } from '../../hooks/trpc'

const AllTheProviders = ({children}) => {
  const queryClient = new QueryClient({
    logger: {
      error: () => {},
      warn: () => {},
      log: () => {},
    },
  })

  const trpcClient = trpc.createClient({
    links: [
      httpLink({
        url: `http://${global.API_DOMAIN_HTTP}/trpc`,
      }),
    ],
  })

  return (
   <trpc.Provider client={trpcClient} queryClient={queryClient}>
        {children}
      </TranslationProvider>
    </trpc.Provider>
  )
}

const customRender = (ui, options) =>
  render(ui, {wrapper: AllTheProviders, ...options})

// re-export everything
export * from '@testing-library/react'

// override render method
export {customRender as render}
```

and that is all you can now use msw-trpc in your test files!

**Comment by ronsigter** [comment]
@maloguertin Hi! 👋 

for this: 

```js
const trpc = createTRPCMsw<AppRouter>()
```

how does this work to replicate:

```js
<trpc.Provider client={trpcClient} queryClient={queryClient}>
        {children}
  </TranslationProvider>
</trpc.Provider>
```

I'm checking the type of `createTRPCMsw` and it does not return `Provider` nor has the ability to instantiate `createClient `

am I missing something? thanks!

**Comment by stubar** [comment]
I'm getting a similar issue, it would be good to see a full working example of this, it's not clear what is happening inside of `'../../hooks/trpc'`
